import type { AgeRange, Lang } from "./data";

/** Welcome-screen openers: 100 per audience and language. Teen pool for "under 18"; the
 * adult pool for "18+" and "prefer not to choose". Each is written in the user's own
 * voice and kept clear of risk wording (see starters.test.ts), so a tap never trips a
 * safety route by itself. Chinese teen topics follow common 12–18 concerns: study and
 * exams, family, friends and exclusion, crushes, body image, phones/games, mood, sleep,
 * the future, school life. 繁體 is generated from the simplified list (ICU Hans-Hant). */
export const TEEN_STARTERS: Record<Lang, readonly string[]> = {
  zh: [
    "期中考砸了，不敢告诉爸妈",
    "中考倒计时，越临近越慌",
    "每天作业写到半夜，好累",
    "月考排名又掉了",
    "上课总走神，听不进去",
    "数学怎么学都学不会",
    "一考试就紧张，脑子一片空白",
    "我好像开始厌学了",
    "爸妈给我报了好多补习班",
    "高考压力好大，怕考不好",
    "学习计划总是坚持不下去",
    "拖到最后一刻才写作业",
    "总被拿来和别人家孩子比",
    "选科不知道该选什么",
    "努力了成绩还是没起色",
    "老师当着全班批评了我",
    "不想去上学，又说不出为什么",
    "竞赛没拿到名次，很失落",
    "假期作业还剩一大堆",
    "考前总是睡不好",
    "爸妈又吵架了，我好烦",
    "跟爸妈一说话就吵起来",
    "爸妈总翻我的手机",
    "觉得爸妈不理解我",
    "爸妈要离婚了，我心里很乱",
    "家里有了二胎，感觉被冷落",
    "爸妈好像只关心我的成绩",
    "想要多一点自己的空间",
    "被爸妈骂了，心里很委屈",
    "爸妈常年在外地，很想他们",
    "和兄弟姐妹总是闹矛盾",
    "爸妈管我管得太严了",
    "家里经济紧张，我有点内疚",
    "有些话不知道怎么跟爸妈开口",
    "奶奶生病住院了，我很担心",
    "好像被同学孤立了",
    "和最好的朋友闹掰了",
    "在班里没有能说话的人",
    "被同学起了难听的外号",
    "有人在背后说我坏话",
    "新学期分班，谁都不认识",
    "不知道怎么融入小团体",
    "朋友总让我帮忙，不好意思拒绝",
    "被同学在群里嘲笑",
    "社交好累，想一个人待会儿",
    "刚开始住校，有点想家",
    "转学之后一直交不到朋友",
    "同桌总是针对我",
    "好朋友有了新朋友，我有点失落",
    "不敢在课上举手发言",
    "我好像喜欢上一个同学了",
    "表白被拒绝了，好难受",
    "分手了，上课都没心思",
    "被传和同学谈恋爱，很尴尬",
    "不知道这算不算喜欢",
    "喜欢的人好像不喜欢我",
    "总觉得自己长得不好看",
    "很在意别人说我胖",
    "青春期身体的变化让我不自在",
    "脸上长痘，不想出门",
    "个子矮，被同学笑",
    "总拿自己和网上的人比",
    "刷手机停不下来",
    "爸妈说我玩游戏太多了",
    "在网上被人骂了，很生气",
    "刷到别人都过得很好，有点难过",
    "网上认识的朋友让我有点不安",
    "手机被没收了，好烦",
    "最近莫名其妙就很烦躁",
    "心里有点乱，想说说",
    "总是忍不住发脾气",
    "动不动就想哭",
    "感觉没人懂我",
    "最近做什么都提不起劲",
    "心里憋着很多话没人说",
    "总担心会发生不好的事",
    "一点小事就想很久",
    "生气的时候管不住嘴",
    "有点孤单，想找个人聊聊",
    "只是想找个人待着",
    "晚上睡不着，越想越清醒",
    "熬夜成习惯了，白天好困",
    "早上起不来，老是迟到",
    "睡前总是胡思乱想",
    "不知道以后想做什么",
    "觉得自己什么都做不好",
    "好像找不到自己的优点",
    "怕让爸妈失望",
    "总觉得别人都比我厉害",
    "想改变自己，不知道从哪开始",
    "对未来很迷茫",
    "总在意别人怎么看我",
    "不喜欢现在的班主任",
    "当班干部压力好大",
    "被老师误会了，好委屈",
    "晚自习太长，坐不住",
    "体育训练好辛苦，想放弃",
    "被选去参加比赛，很紧张",
    "养了很久的猫去世了，很难过",
    "有件事憋在心里，不知道该不该说",
  ],
  "zh-Hant": [
    "期中考砸了，不敢告訴爸媽",
    "中考倒計時，越臨近越慌",
    "每天作業寫到半夜，好累",
    "月考排名又掉了",
    "上課總走神，聽不進去",
    "數學怎麼學都學不會",
    "一考試就緊張，腦子一片空白",
    "我好像開始厭學了",
    "爸媽給我報了好多補習班",
    "高考壓力好大，怕考不好",
    "學習計劃總是堅持不下去",
    "拖到最後一刻才寫作業",
    "總被拿來和別人家孩子比",
    "選科不知道該選什麼",
    "努力了成績還是沒起色",
    "老師當著全班批評了我",
    "不想去上學，又說不出為什麼",
    "競賽沒拿到名次，很失落",
    "假期作業還剩一大堆",
    "考前總是睡不好",
    "爸媽又吵架了，我好煩",
    "跟爸媽一說話就吵起來",
    "爸媽總翻我的手機",
    "覺得爸媽不理解我",
    "爸媽要離婚了，我心裡很亂",
    "家裡有了二胎，感覺被冷落",
    "爸媽好像只關心我的成績",
    "想要多一點自己的空間",
    "被爸媽罵了，心裡很委屈",
    "爸媽常年在外地，很想他們",
    "和兄弟姐妹總是鬧矛盾",
    "爸媽管我管得太嚴了",
    "家裡經濟緊張，我有點內疚",
    "有些話不知道怎麼跟爸媽開口",
    "奶奶生病住院了，我很擔心",
    "好像被同學孤立了",
    "和最好的朋友鬧掰了",
    "在班裡沒有能說話的人",
    "被同學起了難聽的外號",
    "有人在背後說我壞話",
    "新學期分班，誰都不認識",
    "不知道怎麼融入小團體",
    "朋友總讓我幫忙，不好意思拒絕",
    "被同學在群里嘲笑",
    "社交好累，想一個人待會兒",
    "剛開始住校，有點想家",
    "轉學之後一直交不到朋友",
    "同桌總是針對我",
    "好朋友有了新朋友，我有點失落",
    "不敢在課上舉手發言",
    "我好像喜歡上一個同學了",
    "表白被拒絕了，好難受",
    "分手了，上課都沒心思",
    "被傳和同學談戀愛，很尷尬",
    "不知道這算不算喜歡",
    "喜歡的人好像不喜歡我",
    "總覺得自己長得不好看",
    "很在意別人說我胖",
    "青春期身體的變化讓我不自在",
    "臉上長痘，不想出門",
    "個子矮，被同學笑",
    "總拿自己和網上的人比",
    "刷手機停不下來",
    "爸媽說我玩遊戲太多了",
    "在網上被人罵了，很生氣",
    "刷到別人都過得很好，有點難過",
    "網上認識的朋友讓我有點不安",
    "手機被沒收了，好煩",
    "最近莫名其妙就很煩躁",
    "心裡有點亂，想說說",
    "總是忍不住發脾氣",
    "動不動就想哭",
    "感覺沒人懂我",
    "最近做什麼都提不起勁",
    "心裡憋著很多話沒人說",
    "總擔心會發生不好的事",
    "一點小事就想很久",
    "生氣的時候管不住嘴",
    "有點孤單，想找個人聊聊",
    "只是想找個人待著",
    "晚上睡不著，越想越清醒",
    "熬夜成習慣了，白天好困",
    "早上起不來，老是遲到",
    "睡前總是胡思亂想",
    "不知道以後想做什麼",
    "覺得自己什麼都做不好",
    "好像找不到自己的優點",
    "怕讓爸媽失望",
    "總覺得別人都比我厲害",
    "想改變自己，不知道從哪開始",
    "對未來很迷茫",
    "總在意別人怎麼看我",
    "不喜歡現在的班主任",
    "當班幹部壓力好大",
    "被老師誤會了，好委屈",
    "晚自習太長，坐不住",
    "體育訓練好辛苦，想放棄",
    "被選去參加比賽，很緊張",
    "養了很久的貓去世了，很難過",
    "有件事憋在心裡，不知道該不該說",
  ],
  en: [
    "Bombed my midterm and I'm scared to tell my parents",
    "Entrance exams are coming and I'm panicking more every day",
    "Homework keeps me up past midnight every day",
    "My class ranking dropped again",
    "I keep zoning out in class",
    "No matter how hard I try, I can't get math",
    "My mind goes blank in every exam",
    "I think I'm starting to hate school",
    "My parents signed me up for so many tutoring classes",
    "University entrance exams are so much pressure",
    "I can never stick to a study plan",
    "I always leave homework to the last minute",
    "I'm always compared to other kids",
    "I don't know which subjects to choose",
    "I work hard but my grades won't improve",
    "A teacher criticized me in front of the whole class",
    "I don't want to go to school, but I can't say why",
    "I didn't place in the competition and I'm let down",
    "I still have a mountain of holiday homework",
    "I never sleep well before exams",
    "My parents are fighting again and it's getting to me",
    "Every talk with my parents turns into a fight",
    "My parents keep going through my phone",
    "I feel like my parents don't get me",
    "My parents are getting divorced and my head's a mess",
    "Since my sibling was born, I feel left out",
    "My parents only seem to care about my grades",
    "I want a bit more space of my own",
    "My parents yelled at me and it feels so unfair",
    "My parents work far away and I miss them",
    "I'm always clashing with my siblings",
    "My parents are way too strict",
    "Money's tight at home and I feel guilty",
    "There are things I don't know how to tell my parents",
    "My grandma is in the hospital and I'm worried",
    "I think my classmates are leaving me out",
    "I fell out with my best friend",
    "There's no one in my class I can talk to",
    "Classmates gave me a mean nickname",
    "Someone is talking about me behind my back",
    "New class this term and I don't know anyone",
    "I don't know how to fit in with the groups",
    "My friends always ask for favors and I can't say no",
    "Classmates made fun of me in the group chat",
    "Socializing is exhausting, I want some time alone",
    "I just started boarding school and I'm a bit homesick",
    "I changed schools and still haven't made friends",
    "My deskmate keeps picking on me",
    "My best friend has a new friend and I feel left behind",
    "I'm too scared to raise my hand in class",
    "I think I have a crush on a classmate",
    "I confessed and got turned down, it hurts",
    "We broke up and I can't focus in class",
    "There's a rumor I'm dating someone and it's awkward",
    "I'm not sure if this counts as liking someone",
    "The person I like doesn't seem to like me back",
    "I keep thinking I don't look good",
    "It really bothers me when people comment on my weight",
    "The changes in my body during puberty make me uncomfortable",
    "I've got acne and don't want to go out",
    "Classmates laugh at me for being short",
    "I keep comparing myself to people online",
    "I can't stop scrolling on my phone",
    "My parents say I game too much",
    "Someone insulted me online and I'm angry",
    "Everyone online seems to have a great life and it gets me down",
    "Someone I met online is making me a bit uneasy",
    "My phone got taken away and I'm so annoyed",
    "I've been irritable lately for no reason",
    "My mind's a bit messy, I want to talk",
    "I keep losing my temper",
    "I tear up at the smallest things",
    "I feel like no one understands me",
    "Lately I can't get into anything",
    "I've got so much bottled up and no one to tell",
    "I keep worrying something bad will happen",
    "I overthink every little thing",
    "I say things I regret when I'm angry",
    "I'm a bit lonely and want someone to talk to",
    "I just want some company",
    "I can't sleep, the more I think the more awake I get",
    "Staying up late is a habit now and I'm sleepy all day",
    "I can't get up in the morning and I'm always late",
    "My mind races before bed",
    "I don't know what I want to do in the future",
    "I feel like I can't do anything right",
    "I can't seem to find anything I'm good at",
    "I'm afraid of disappointing my parents",
    "Everyone else seems better than me",
    "I want to change but don't know where to start",
    "I feel lost about the future",
    "I care too much about what others think of me",
    "I don't get along with my homeroom teacher",
    "Being class monitor is a lot of pressure",
    "A teacher misunderstood me and it's so unfair",
    "Evening study hall is so long I can't sit still",
    "Sports training is so hard I want to quit",
    "I was picked for a competition and I'm nervous",
    "My cat passed away and I'm really sad",
    "Something's weighing on me and I don't know if I should say it",
  ],
  ja: [
    "中間テストで失敗して、親に言えない",
    "受験が近づいて、どんどん焦ってきた",
    "毎日宿題が夜中までかかってしんどい",
    "テストの順位がまた下がった",
    "授業中、ぼーっとして頭に入らない",
    "数学がどうしてもわからない",
    "テストになると緊張して頭が真っ白になる",
    "学校に行くのが嫌になってきたかも",
    "親に塾をたくさん入れられた",
    "大学受験のプレッシャーがすごい",
    "勉強の計画がいつも続かない",
    "宿題をいつもギリギリまで後回しにしてしまう",
    "いつも他の子と比べられる",
    "科目選択で迷っている",
    "頑張っても成績が上がらない",
    "先生にみんなの前で注意された",
    "学校に行きたくないけど、理由がうまく言えない",
    "大会で入賞できなくて落ち込んでる",
    "休みの宿題がまだ山ほど残ってる",
    "テスト前はいつもよく眠れない",
    "親がまたケンカしていて、しんどい",
    "親と話すとすぐケンカになる",
    "親にスマホをチェックされる",
    "親にわかってもらえない気がする",
    "親が離婚することになって、気持ちがぐちゃぐちゃ",
    "下にきょうだいが生まれて、放っておかれてる気がする",
    "親は成績のことしか気にしていないみたい",
    "もう少し自分だけの時間と場所がほしい",
    "親に怒られて、モヤモヤしてる",
    "親が遠くで働いていて、さみしい",
    "きょうだいとしょっちゅうもめる",
    "親がきびしすぎる",
    "家がお金に困っていて、申し訳なく思う",
    "親にどう切り出せばいいかわからないことがある",
    "おばあちゃんが入院して心配",
    "クラスで仲間外れにされてる気がする",
    "親友とケンカして気まずくなった",
    "クラスに話せる人がいない",
    "クラスメイトにひどいあだ名をつけられた",
    "陰で悪口を言われている",
    "クラス替えで知ってる人がいない",
    "グループにうまくなじめない",
    "友だちに頼まれると断れない",
    "グループチャットでからかわれた",
    "人付き合いに疲れて、少し一人になりたい",
    "寮生活が始まって、ちょっとホームシック",
    "転校してから友だちができない",
    "隣の席の子にいつも意地悪される",
    "親友に新しい友だちができて、ちょっとさみしい",
    "授業で手を挙げる勇気が出ない",
    "クラスの子を好きになったかも",
    "告白して振られた、つらい",
    "別れてから授業に集中できない",
    "付き合ってるって噂されて気まずい",
    "これが「好き」なのかわからない",
    "好きな人に好かれていない気がする",
    "自分の見た目に自信がない",
    "体型のことを言われるのがすごく気になる",
    "思春期の体の変化が落ち着かない",
    "ニキビができて外に出たくない",
    "背が低いことをからかわれる",
    "ネットの人とつい自分を比べてしまう",
    "スマホを見るのがやめられない",
    "親にゲームのしすぎだと言われる",
    "ネットで悪口を言われて腹が立つ",
    "みんな楽しそうに見えて、少し落ち込む",
    "ネットで知り合った人のことで少し不安",
    "スマホを取り上げられてイライラする",
    "最近なんだかイライラする",
    "頭の中がごちゃごちゃで、話したい",
    "ついカッとなってしまう",
    "すぐ泣きそうになる",
    "誰にもわかってもらえない気がする",
    "最近なにをしてもやる気が出ない",
    "言いたいことがたまっているのに話せる人がいない",
    "何か悪いことが起きそうで心配になる",
    "小さなことをずっと考えてしまう",
    "怒るとつい言いすぎてしまう",
    "ちょっとさみしくて、誰かと話したい",
    "ただ誰かにそばにいてほしい",
    "夜眠れなくて、考えるほど目がさえる",
    "夜ふかしが習慣になって、昼間ずっと眠い",
    "朝起きられなくて、よく遅刻する",
    "寝る前にいろいろ考えてしまう",
    "将来なにをしたいかわからない",
    "自分は何をやってもうまくいかない気がする",
    "自分のいいところが見つからない",
    "親をがっかりさせるのがこわい",
    "まわりのみんなが自分よりすごく見える",
    "変わりたいけど、何から始めればいいかわからない",
    "将来のことを考えると迷ってしまう",
    "人にどう思われているかが気になる",
    "今の担任の先生が苦手",
    "学級委員のプレッシャーが重い",
    "先生に誤解されて悔しい",
    "放課後の自習が長くてじっとしていられない",
    "部活の練習がきつくて、やめたい",
    "大会のメンバーに選ばれて緊張してる",
    "長く飼っていた猫が亡くなって悲しい",
    "胸にしまっていることがあって、話すべきか迷ってる",
  ],
  ko: [
    "중간고사를 망쳐서 부모님께 말을 못 하겠어",
    "시험이 다가올수록 점점 불안해",
    "매일 숙제하느라 밤늦게까지 깨어 있어서 힘들어",
    "성적 순위가 또 떨어졌어",
    "수업 시간에 자꾸 딴생각이 나",
    "수학은 아무리 해도 모르겠어",
    "시험만 보면 긴장해서 머리가 하얘져",
    "학교 가기가 싫어지는 것 같아",
    "부모님이 학원을 너무 많이 보내",
    "수능 부담이 너무 커",
    "공부 계획을 끝까지 못 지켜",
    "숙제를 늘 마지막까지 미뤄",
    "다른 집 애랑 자꾸 비교당해",
    "선택 과목을 뭘 골라야 할지 모르겠어",
    "열심히 해도 성적이 안 올라",
    "선생님이 반 애들 앞에서 나를 혼냈어",
    "학교에 가기 싫은데 이유를 설명 못 하겠어",
    "대회에서 상을 못 받아서 속상해",
    "방학 숙제가 아직 산더미야",
    "시험 전에는 잠을 잘 못 자",
    "부모님이 또 싸워서 마음이 복잡해",
    "부모님이랑 말만 하면 싸우게 돼",
    "부모님이 내 휴대폰을 자꾸 확인해",
    "부모님이 나를 이해 못 하는 것 같아",
    "부모님이 이혼한대, 마음이 너무 복잡해",
    "동생이 생기고 나서 소외감이 들어",
    "부모님은 내 성적에만 관심 있는 것 같아",
    "나만의 공간이 조금 더 있었으면 좋겠어",
    "부모님께 혼나서 너무 억울해",
    "부모님이 멀리서 일하셔서 보고 싶어",
    "형제자매랑 자꾸 다퉈",
    "부모님이 너무 엄해",
    "집에 돈 문제가 있어서 미안한 마음이 들어",
    "부모님께 어떻게 말을 꺼내야 할지 모르겠어",
    "할머니가 입원하셔서 걱정돼",
    "반에서 따돌림당하는 것 같아",
    "제일 친한 친구랑 사이가 틀어졌어",
    "반에 이야기할 사람이 없어",
    "친구들이 나한테 기분 나쁜 별명을 붙였어",
    "누가 뒤에서 내 욕을 해",
    "반이 바뀌어서 아는 사람이 아무도 없어",
    "무리에 어떻게 끼어야 할지 모르겠어",
    "친구 부탁을 거절을 못 하겠어",
    "단톡방에서 놀림을 받았어",
    "사람 만나는 게 지쳐서 혼자 있고 싶어",
    "기숙사 생활을 시작했는데 집이 그리워",
    "전학 오고 나서 친구를 못 사귀었어",
    "짝꿍이 자꾸 나를 괴롭혀",
    "친한 친구한테 새 친구가 생겨서 좀 서운해",
    "수업 시간에 손 들 용기가 안 나",
    "같은 반 애를 좋아하게 된 것 같아",
    "고백했다가 거절당해서 너무 속상해",
    "헤어지고 나서 수업에 집중이 안 돼",
    "누구랑 사귄다는 소문이 나서 민망해",
    "이게 좋아하는 건지 잘 모르겠어",
    "좋아하는 사람은 나를 안 좋아하는 것 같아",
    "내 외모가 별로인 것 같아",
    "몸무게 얘기를 들으면 너무 신경 쓰여",
    "사춘기 몸의 변화가 불편해",
    "여드름 때문에 밖에 나가기 싫어",
    "키가 작다고 놀림받아",
    "자꾸 SNS 속 사람들이랑 나를 비교해",
    "휴대폰을 놓을 수가 없어",
    "부모님이 게임을 너무 많이 한대",
    "인터넷에서 욕을 먹어서 화가 나",
    "다른 사람들은 다 잘 사는 것 같아서 기분이 처져",
    "인터넷에서 알게 된 사람 때문에 좀 불안해",
    "휴대폰을 뺏겨서 짜증 나",
    "요즘 괜히 짜증이 나",
    "마음이 좀 복잡해서 이야기하고 싶어",
    "자꾸 화를 참지 못해",
    "툭하면 눈물이 나",
    "아무도 나를 이해 못 하는 것 같아",
    "요즘 뭘 해도 의욕이 없어",
    "하고 싶은 말이 쌓였는데 털어놓을 사람이 없어",
    "나쁜 일이 생길까 봐 자꾸 걱정돼",
    "작은 일도 계속 곱씹게 돼",
    "화나면 말을 너무 심하게 해",
    "좀 외로워서 누구랑 얘기하고 싶어",
    "그냥 누가 곁에 있어 줬으면 좋겠어",
    "밤에 잠이 안 오고 생각할수록 정신이 말똥말똥해",
    "밤새는 게 습관이 돼서 낮에 너무 졸려",
    "아침에 못 일어나서 자꾸 지각해",
    "자기 전에 이런저런 생각이 많아",
    "앞으로 뭘 하고 싶은지 모르겠어",
    "나는 뭘 해도 잘 못하는 것 같아",
    "내 장점을 못 찾겠어",
    "부모님을 실망시킬까 봐 무서워",
    "다른 애들이 다 나보다 잘난 것 같아",
    "바뀌고 싶은데 어디서부터 해야 할지 모르겠어",
    "미래가 막막해",
    "남들이 나를 어떻게 보는지 너무 신경 쓰여",
    "지금 담임 선생님이 불편해",
    "반장 하는 게 부담돼",
    "선생님이 오해하셔서 억울해",
    "야간 자율학습이 너무 길어서 앉아 있기 힘들어",
    "운동부 훈련이 너무 힘들어서 그만두고 싶어",
    "대회에 나가게 돼서 긴장돼",
    "오래 키운 고양이가 떠나서 너무 슬퍼",
    "마음에 담아 둔 일이 있는데 말해도 될지 모르겠어",
  ],
  es: [
    "Me fue fatal el examen y no me atrevo a decírselo a mis padres",
    "Se acercan los exámenes de acceso y cada día me agobio más",
    "Hago deberes hasta medianoche todos los días, qué cansancio",
    "He vuelto a bajar en el ranking de la clase",
    "En clase me distraigo todo el rato",
    "Por más que estudio, no entiendo las mates",
    "En los exámenes me pongo de los nervios y me quedo en blanco",
    "Creo que estoy empezando a odiar el instituto",
    "Mis padres me han apuntado a un montón de clases particulares",
    "La presión por la selectividad es enorme",
    "Nunca consigo seguir mi plan de estudio",
    "Siempre dejo los deberes para el último momento",
    "Siempre me comparan con otros chicos",
    "No sé qué optativas elegir",
    "Me esfuerzo y aun así no subo las notas",
    "Un profe me regañó delante de toda la clase",
    "No quiero ir al instituto, pero no sé explicar por qué",
    "No quedé entre los primeros en la competición y estoy de bajón",
    "Todavía me queda un montón de deberes de vacaciones",
    "Antes de los exámenes nunca duermo bien",
    "Mis padres han vuelto a discutir y me afecta",
    "Cada vez que hablo con mis padres acabamos discutiendo",
    "Mis padres me revisan el móvil",
    "Siento que mis padres no me entienden",
    "Mis padres se van a divorciar y tengo un lío en la cabeza",
    "Desde que nació mi hermano siento que me dejan de lado",
    "Parece que a mis padres solo les importan mis notas",
    "Me gustaría tener un poco más de espacio propio",
    "Mis padres me echaron la bronca y me parece injusto",
    "Mis padres trabajan lejos y los echo de menos",
    "Siempre estoy peleando con mis hermanos",
    "Mis padres son demasiado estrictos",
    "En casa vamos justos de dinero y me siento culpable",
    "Hay cosas que no sé cómo contarles a mis padres",
    "Mi abuela está en el hospital y me preocupa",
    "Creo que mis compañeros me están dejando de lado",
    "Me peleé con mi mejor amigo",
    "No tengo a nadie con quien hablar en clase",
    "Unos compañeros me han puesto un mote feo",
    "Alguien habla mal de mí a mis espaldas",
    "Este curso me cambiaron de clase y no conozco a nadie",
    "No sé cómo encajar en los grupos",
    "Mis amigos siempre me piden favores y no sé decir que no",
    "Se rieron de mí en el grupo de clase",
    "Socializar me agota, quiero estar un rato a mi aire",
    "Acabo de empezar en un internado y echo de menos mi casa",
    "Me cambié de instituto y aún no tengo amigos",
    "Mi compañero de pupitre siempre va a por mí",
    "Mi mejor amigo tiene un amigo nuevo y me siento apartado",
    "Me da miedo levantar la mano en clase",
    "Creo que me gusta alguien de mi clase",
    "Me declaré y me dijeron que no, duele mucho",
    "Lo dejamos y no puedo concentrarme en clase",
    "Dicen que salgo con alguien y me da mucha vergüenza",
    "No sé si esto que siento es que me gusta",
    "La persona que me gusta no parece interesada en mí",
    "Siempre pienso que no me veo bien",
    "Me molesta muchísimo que comenten mi peso",
    "Los cambios de mi cuerpo en la pubertad me incomodan",
    "Tengo granos y no quiero salir de casa",
    "Se ríen de mí por mi estatura",
    "Siempre me comparo con la gente de internet",
    "No puedo dejar de mirar el móvil",
    "Mis padres dicen que juego demasiado a los videojuegos",
    "Me insultaron por internet y me ha sentado fatal",
    "En redes todos parecen felices y eso me pone de bajón",
    "Alguien que conocí por internet me da mala espina",
    "Me quitaron el móvil y estoy de mal humor",
    "Últimamente me irrito sin motivo",
    "Tengo la cabeza hecha un lío y quiero hablar",
    "Siempre acabo perdiendo los nervios",
    "Lloro por cualquier cosa",
    "Siento que nadie me entiende",
    "Últimamente nada me motiva",
    "Tengo muchas cosas guardadas y nadie a quien contárselas",
    "Me preocupa que vaya a pasar algo malo",
    "Le doy mil vueltas a cualquier tontería",
    "Cuando me enfado digo cosas de las que me arrepiento",
    "Hoy me pesa la soledad y quiero hablar con alguien",
    "Solo quiero un poco de compañía",
    "No puedo dormir: cuanto más pienso, más se me quita el sueño",
    "Trasnochar se ha vuelto costumbre y me paso el día con sueño",
    "No consigo levantarme por la mañana y siempre llego tarde",
    "Antes de dormir me vienen mil pensamientos",
    "No sé qué quiero hacer en el futuro",
    "Siento que todo me sale mal",
    "No consigo encontrar lo que se me da bien",
    "Me da miedo decepcionar a mis padres",
    "Parece que todos son mejores que yo",
    "Quiero cambiar, pero no sé por dónde empezar",
    "No tengo nada claro el futuro",
    "Me importa demasiado lo que piensen de mí",
    "No me llevo bien con mi tutor de este año",
    "Ser delegado de clase me agobia",
    "Un profe me malinterpretó y me parece injusto",
    "Las horas de estudio por la tarde se me hacen eternas",
    "Los entrenamientos son tan duros que quiero dejarlo",
    "Me eligieron para una competición y me tiemblan las piernas",
    "Se murió mi gato de toda la vida y estoy muy triste",
    "Tengo algo guardado y no sé si debería contarlo",
  ],
  fr: [
    "J’ai raté mon contrôle et je n’ose pas le dire à mes parents",
    "Le brevet approche et je stresse de plus en plus",
    "Je fais mes devoirs jusqu’à minuit tous les soirs, c’est épuisant",
    "J’ai encore baissé dans le classement",
    "En cours, je décroche tout le temps",
    "J’ai beau travailler, je ne comprends rien aux maths",
    "En contrôle, je stresse et j’ai un trou noir",
    "Je crois que je commence à détester l’école",
    "Mes parents m’ont inscrit à plein de cours de soutien",
    "La pression du bac est énorme",
    "Je n’arrive jamais à tenir mon planning de révisions",
    "Je fais toujours mes devoirs à la dernière minute",
    "On me compare toujours aux autres",
    "Je ne sais pas quelles spécialités choisir",
    "Je travaille dur mais mes notes ne remontent pas",
    "Un prof m’a fait une remarque devant toute la classe",
    "Je n’ai pas envie d’aller en cours, mais je ne sais pas expliquer pourquoi",
    "Je n’ai pas été classé au concours et je suis déçu",
    "Il me reste une montagne de devoirs de vacances",
    "Je dors toujours mal avant les contrôles",
    "Mes parents se disputent encore et ça me pèse",
    "Dès que je parle avec mes parents, on se dispute",
    "Mes parents fouillent mon téléphone",
    "J’ai l’impression que mes parents ne me comprennent pas",
    "Mes parents vont divorcer et j’ai la tête en vrac",
    "Depuis la naissance du bébé, je me sens mis de côté",
    "On dirait que mes parents ne s’intéressent qu’à mes notes",
    "J’aimerais avoir un peu plus d’espace à moi",
    "Mes parents m’ont crié dessus et je trouve ça injuste",
    "Mes parents travaillent loin et ils me manquent",
    "Je me dispute tout le temps avec mes frères et sœurs",
    "Mes parents sont beaucoup trop stricts",
    "À la maison, l’argent manque et je culpabilise",
    "Il y a des choses que je ne sais pas comment dire à mes parents",
    "Ma grand-mère est à l’hôpital et je m’inquiète",
    "J’ai l’impression d’être mis à l’écart en classe",
    "Je me suis fâché avec mon meilleur ami",
    "Je n’ai personne à qui parler dans ma classe",
    "Des élèves m’ont donné un surnom méchant",
    "Quelqu’un dit du mal de moi dans mon dos",
    "Nouvelle classe cette année, je ne connais personne",
    "Je ne sais pas comment m’intégrer aux groupes",
    "Mes amis me demandent toujours des services et je n’ose pas dire non",
    "On s’est moqué de moi sur le groupe de la classe",
    "Voir du monde m’épuise, j’ai besoin d’un moment au calme",
    "Je viens d’entrer à l’internat et ma famille me manque",
    "J’ai changé d’école et je n’ai toujours pas d’amis",
    "Mon voisin de table s’en prend toujours à moi",
    "Mon meilleur ami a un nouveau pote et je me sens délaissé",
    "Je n’ose pas lever la main en cours",
    "Je crois que je suis amoureux de quelqu’un de ma classe",
    "J’ai fait une déclaration et on m’a dit non, ça fait mal",
    "On a rompu et je n’arrive plus à me concentrer en cours",
    "On raconte que je sors avec quelqu’un et c’est gênant",
    "Je ne sais pas si c’est vraiment de l’amour",
    "La personne que j’aime ne semble pas s’intéresser à moi",
    "Je n’aime pas mon apparence",
    "Ça me touche beaucoup quand on commente mon poids",
    "Les changements de mon corps à la puberté me mettent mal à l’aise",
    "J’ai des boutons et je n’ai pas envie de sortir",
    "On se moque de moi à cause de ma taille",
    "Je me compare toujours aux gens sur les réseaux",
    "Je n’arrive pas à lâcher mon téléphone",
    "Mes parents disent que je joue trop aux jeux vidéo",
    "On m’a insulté en ligne et ça m’énerve",
    "Sur les réseaux, tout le monde a l’air heureux et ça me plombe un peu",
    "Quelqu’un rencontré en ligne me met un peu mal à l’aise",
    "On m’a confisqué mon téléphone et ça m’énerve",
    "Ces temps-ci, je m’énerve sans raison",
    "J’ai la tête un peu en vrac, j’ai envie d’en parler",
    "Je m’emporte tout le temps",
    "Je pleure pour un rien",
    "J’ai l’impression que personne ne me comprend",
    "En ce moment, rien ne me motive",
    "J’ai plein de choses sur le cœur et personne à qui les dire",
    "J’ai peur qu’il arrive quelque chose de grave",
    "Je rumine pour la moindre petite chose",
    "Quand je suis en colère, je dis des choses que je regrette",
    "Je me sens un peu seul et j’ai envie de parler à quelqu’un",
    "J’ai juste besoin de compagnie",
    "Je n’arrive pas à dormir, plus je réfléchis plus je suis réveillé",
    "Me coucher tard est devenu une habitude et je somnole toute la journée",
    "Je n’arrive pas à me lever le matin et je suis souvent en retard",
    "Avant de dormir, mes pensées partent dans tous les sens",
    "Je ne sais pas ce que je veux faire plus tard",
    "J’ai l’impression de tout rater",
    "Je n’arrive pas à trouver mes qualités",
    "J’ai peur de décevoir mes parents",
    "Tout le monde a l’air plus fort que moi",
    "Je veux changer mais je ne sais pas par où commencer",
    "L’avenir me semble flou",
    "Je fais trop attention à ce que les autres pensent de moi",
    "Je ne m’entends pas avec mon prof principal",
    "Être délégué de classe me met la pression",
    "Un prof m’a mal compris et je trouve ça injuste",
    "L’étude du soir est si longue que je n’arrive pas à rester assis",
    "Les entraînements sont si durs que j’ai envie d’arrêter",
    "J’ai été sélectionné pour une compétition et je stresse",
    "Mon chat que j’avais depuis des années est mort, je suis très triste",
    "J’ai quelque chose sur le cœur et je ne sais pas si je dois en parler",
  ],
  de: [
    "Ich habe die Klassenarbeit verhauen und traue mich nicht, es meinen Eltern zu sagen",
    "Die Abschlussprüfungen rücken näher und ich werde immer nervöser",
    "Ich sitze jeden Tag bis Mitternacht an den Hausaufgaben",
    "Meine Noten sind schon wieder abgerutscht",
    "Im Unterricht bin ich ständig mit den Gedanken woanders",
    "Egal wie viel ich lerne, Mathe verstehe ich nicht",
    "In Prüfungen werde ich nervös und habe ein Blackout",
    "Ich glaube, ich fange an, Schule zu hassen",
    "Meine Eltern haben mich bei ganz vielen Nachhilfekursen angemeldet",
    "Der Druck wegen des Abis ist riesig",
    "Ich halte meinen Lernplan nie durch",
    "Ich schiebe Hausaufgaben immer bis zur letzten Minute auf",
    "Ich werde ständig mit anderen verglichen",
    "Ich weiß nicht, welche Fächer ich wählen soll",
    "Ich strenge mich an, aber meine Noten werden nicht besser",
    "Ein Lehrer hat mich vor der ganzen Klasse kritisiert",
    "Ich will nicht in die Schule, kann aber nicht sagen, warum",
    "Ich habe beim Wettbewerb nicht gut abgeschnitten und bin enttäuscht",
    "Ich habe noch einen riesigen Berg Ferienaufgaben",
    "Vor Prüfungen schlafe ich immer schlecht",
    "Meine Eltern streiten schon wieder und das belastet mich",
    "Sobald ich mit meinen Eltern rede, gibt es Streit",
    "Meine Eltern kontrollieren mein Handy",
    "Ich habe das Gefühl, meine Eltern verstehen mich nicht",
    "Meine Eltern lassen sich scheiden und in meinem Kopf ist Chaos",
    "Seit mein Geschwisterchen da ist, fühle ich mich übersehen",
    "Meinen Eltern scheinen nur meine Noten wichtig zu sein",
    "Ich hätte gern ein bisschen mehr eigenen Freiraum",
    "Meine Eltern haben mich angeschrien und ich finde das unfair",
    "Meine Eltern arbeiten weit weg und ich vermisse sie",
    "Ich streite mich ständig mit meinen Geschwistern",
    "Meine Eltern sind viel zu streng",
    "Bei uns ist das Geld knapp und ich fühle mich schuldig",
    "Es gibt Dinge, die ich meinen Eltern nicht zu sagen weiß",
    "Meine Oma liegt im Krankenhaus und ich mache mir Sorgen",
    "Ich glaube, meine Mitschüler grenzen mich aus",
    "Ich habe mich mit meinem besten Freund zerstritten",
    "In meiner Klasse habe ich niemanden zum Reden",
    "Mitschüler haben mir einen gemeinen Spitznamen gegeben",
    "Jemand lästert hinter meinem Rücken über mich",
    "Neue Klasse in diesem Schuljahr und ich kenne niemanden",
    "Ich weiß nicht, wie ich in die Gruppen reinkomme",
    "Freunde bitten mich ständig um Gefallen und ich kann nicht Nein sagen",
    "In der Klassengruppe haben sich alle über mich lustig gemacht",
    "Unter Leuten sein strengt mich an, ich will kurz meine Ruhe",
    "Ich bin gerade ins Internat gekommen und habe Heimweh",
    "Seit dem Schulwechsel habe ich keine Freunde gefunden",
    "Mein Sitznachbar hackt ständig auf mir herum",
    "Mein bester Freund hat einen neuen Kumpel und ich fühle mich außen vor",
    "Ich traue mich nicht, mich im Unterricht zu melden",
    "Ich glaube, ich bin in jemanden aus meiner Klasse verliebt",
    "Ich habe meine Gefühle gestanden und einen Korb bekommen",
    "Wir haben Schluss gemacht und ich kann mich im Unterricht nicht konzentrieren",
    "Es geht das Gerücht, dass ich mit jemandem zusammen bin, das ist peinlich",
    "Ich weiß nicht, ob das wirklich Verliebtsein ist",
    "Die Person, die ich mag, scheint mich nicht zu mögen",
    "Ich mag mein Aussehen nicht",
    "Es trifft mich sehr, wenn jemand mein Gewicht kommentiert",
    "Die Veränderungen meines Körpers in der Pubertät sind mir unangenehm",
    "Ich habe Pickel und will nicht rausgehen",
    "Ich werde ausgelacht, weil ich klein bin",
    "Ich vergleiche mich ständig mit Leuten im Netz",
    "Ich komme vom Handy nicht los",
    "Meine Eltern sagen, ich zocke zu viel",
    "Ich wurde online beleidigt und bin wütend",
    "Im Netz wirken alle glücklich und das zieht mich runter",
    "Jemand, den ich online kennengelernt habe, macht mich unsicher",
    "Mein Handy wurde mir weggenommen und ich bin genervt",
    "In letzter Zeit bin ich ohne Grund gereizt",
    "In meinem Kopf ist alles durcheinander, ich will reden",
    "Ich verliere ständig die Beherrschung",
    "Ich muss bei jeder Kleinigkeit weinen",
    "Ich habe das Gefühl, niemand versteht mich",
    "Gerade kann ich mich für nichts aufraffen",
    "Ich habe so viel auf dem Herzen und niemanden zum Reden",
    "Ich habe Angst, dass etwas Schlimmes passiert",
    "Ich denke über jede Kleinigkeit ewig nach",
    "Wenn ich wütend bin, sage ich Dinge, die ich bereue",
    "Ich fühle mich etwas einsam und möchte mit jemandem reden",
    "Ich hätte einfach gern etwas Gesellschaft",
    "Ich kann nicht schlafen, je mehr ich nachdenke, desto wacher werde ich",
    "Lange aufbleiben ist zur Gewohnheit geworden und tagsüber bin ich müde",
    "Morgens komme ich nicht aus dem Bett und bin oft zu spät",
    "Vor dem Einschlafen kreisen meine Gedanken",
    "Ich weiß nicht, was ich später machen will",
    "Ich habe das Gefühl, ich kriege nichts hin",
    "Ich finde keine Stärken an mir",
    "Ich habe Angst, meine Eltern zu enttäuschen",
    "Alle anderen wirken besser als ich",
    "Ich will mich ändern, weiß aber nicht, wo ich anfangen soll",
    "Wenn ich an die Zukunft denke, bin ich ratlos",
    "Mir ist zu wichtig, was andere über mich denken",
    "Ich komme mit der Klassenleitung nicht klar",
    "Klassensprecher zu sein setzt mich unter Druck",
    "Ein Lehrer hat mich missverstanden und das ist unfair",
    "Die Lernzeit am Nachmittag ist so lang, ich kann nicht stillsitzen",
    "Das Training ist so hart, dass ich aufhören will",
    "Ich wurde für einen Wettbewerb ausgewählt und bin nervös",
    "Meine Katze, die ich seit Jahren hatte, ist gestorben und ich bin sehr traurig",
    "Mich beschäftigt etwas und ich weiß nicht, ob ich es sagen soll",
  ],
};

export const ADULT_STARTERS: Record<Lang, readonly string[]> = {
  zh: [
    "工作压力大，整个人绷得很紧",
    "每天加班，感觉被掏空",
    "领导总是挑我的错",
    "和同事相处很累",
    "想辞职又不敢",
    "刚失业，很焦虑",
    "找工作屡屡碰壁",
    "不知道这份工作还要不要坚持",
    "升职没轮到我，很失落",
    "工作没有成就感",
    "一开会发言就紧张",
    "下班了脑子还停不下来",
    "职场新人，什么都不会",
    "周日晚上就开始焦虑上班",
    "被安排了做不完的任务",
    "考研压力很大",
    "考公考了几次都没上岸",
    "毕业了不知道往哪走",
    "论文进度卡住了",
    "读研读得很迷茫",
    "和伴侣总是吵架",
    "刚分手，放不下",
    "异地恋好累",
    "感觉另一半不在乎我",
    "被催婚，压力好大",
    "婚后生活和想象的不一样",
    "不知道该不该继续这段关系",
    "单身久了，有点孤单",
    "总是在关系里委屈自己",
    "发现伴侣有事瞒着我",
    "和父母沟通总是不愉快",
    "父母年纪大了，很担心他们",
    "原生家庭的影响一直都在",
    "当了父母，觉得力不从心",
    "孩子不听话，我快没耐心了",
    "带娃和工作两头顾不上",
    "和家人观念差太多",
    "家里的事都压在我身上",
    "照顾生病的家人很疲惫",
    "过年回家有点发怵",
    "来到新城市，一个朋友都没有",
    "朋友越来越少了",
    "社交场合总是很尴尬",
    "不懂怎么拒绝别人",
    "总觉得自己在讨好别人",
    "下班后只想一个人待着",
    "和老朋友渐渐疏远了",
    "在人群里也觉得孤单",
    "最近心里有点乱，想说说",
    "总是莫名焦虑",
    "情绪低落有一阵子了",
    "容易被小事激怒",
    "心里很累，但说不清为什么",
    "总是担心最坏的情况",
    "脑子里停不下来地想事情",
    "一个人的时候特别容易难过",
    "感觉自己一直在内耗",
    "情绪上来了不知道怎么办",
    "我最近睡不太好",
    "半夜总醒，醒了就睡不着",
    "每天都觉得很疲惫",
    "作息乱了，调不回来",
    "压力大的时候就吃很多",
    "总担心自己的身体出问题",
    "觉得自己一事无成",
    "总是和同龄人比较",
    "三十岁了还很迷茫",
    "对自己要求太高，停不下来",
    "很难接受自己的不完美",
    "不知道自己真正想要什么",
    "总觉得自己不够好",
    "想做出改变，又总在原地",
    "很在意别人的评价",
    "自信心越来越低",
    "经济压力让我很焦虑",
    "房贷压得我好累",
    "存不下钱，很没安全感",
    "搬家后一直适应不了",
    "生活好像只剩上班和睡觉",
    "每天都过得一模一样",
    "亲人去世后一直走不出来",
    "宠物不在了，心里空落落的",
    "经历了一些变故，还没缓过来",
    "一段友谊结束了，很失落",
    "只是想找个人待着",
    "想聊聊最近的烦心事",
    "拖延越来越严重",
    "做决定总是犹豫不决",
    "总是忍不住刷手机到很晚",
    "生气的时候容易说重话",
    "不好意思开口请别人帮忙",
    "想学会好好照顾自己",
    "压力大时不知道怎么放松",
    "有件事一直放不下",
    "害怕冲突，总是忍着",
    "和朋友因为借钱闹僵了",
    "感觉被同事排挤",
    "产假结束要回去上班了，很忐忑",
    "退休后不知道做什么好",
    "心里有个结，想理一理",
  ],
  "zh-Hant": [
    "工作壓力大，整個人繃得很緊",
    "每天加班，感覺被掏空",
    "領導總是挑我的錯",
    "和同事相處很累",
    "想辭職又不敢",
    "剛失業，很焦慮",
    "找工作屢屢碰壁",
    "不知道這份工作還要不要堅持",
    "升職沒輪到我，很失落",
    "工作沒有成就感",
    "一開會發言就緊張",
    "下班了腦子還停不下來",
    "職場新人，什麼都不會",
    "周日晚上就開始焦慮上班",
    "被安排了做不完的任務",
    "考研壓力很大",
    "考公考了幾次都沒上岸",
    "畢業了不知道往哪走",
    "論文進度卡住了",
    "讀研讀得很迷茫",
    "和伴侶總是吵架",
    "剛分手，放不下",
    "異地戀好累",
    "感覺另一半不在乎我",
    "被催婚，壓力好大",
    "婚後生活和想象的不一樣",
    "不知道該不該繼續這段關係",
    "單身久了，有點孤單",
    "總是在關係里委屈自己",
    "發現伴侶有事瞞著我",
    "和父母溝通總是不愉快",
    "父母年紀大了，很擔心他們",
    "原生家庭的影響一直都在",
    "當了父母，覺得力不從心",
    "孩子不聽話，我快沒耐心了",
    "帶娃和工作兩頭顧不上",
    "和家人觀念差太多",
    "家裡的事都壓在我身上",
    "照顧生病的家人很疲憊",
    "過年回家有點發怵",
    "來到新城市，一個朋友都沒有",
    "朋友越來越少了",
    "社交場合總是很尷尬",
    "不懂怎麼拒絕別人",
    "總覺得自己在討好別人",
    "下班後只想一個人待著",
    "和老朋友漸漸疏遠了",
    "在人群里也覺得孤單",
    "最近心裡有點亂，想說說",
    "總是莫名焦慮",
    "情緒低落有一陣子了",
    "容易被小事激怒",
    "心裡很累，但說不清為什麼",
    "總是擔心最壞的情況",
    "腦子里停不下來地想事情",
    "一個人的時候特別容易難過",
    "感覺自己一直在內耗",
    "情緒上來了不知道怎麼辦",
    "我最近睡不太好",
    "半夜總醒，醒了就睡不著",
    "每天都覺得很疲憊",
    "作息亂了，調不回來",
    "壓力大的時候就吃很多",
    "總擔心自己的身體出問題",
    "覺得自己一事無成",
    "總是和同齡人比較",
    "三十歲了還很迷茫",
    "對自己要求太高，停不下來",
    "很難接受自己的不完美",
    "不知道自己真正想要什麼",
    "總覺得自己不夠好",
    "想做出改變，又總在原地",
    "很在意別人的評價",
    "自信心越來越低",
    "經濟壓力讓我很焦慮",
    "房貸壓得我好累",
    "存不下錢，很沒安全感",
    "搬家後一直適應不了",
    "生活好像只剩上班和睡覺",
    "每天都過得一模一樣",
    "親人去世後一直走不出來",
    "寵物不在了，心裡空落落的",
    "經歷了一些變故，還沒緩過來",
    "一段友誼結束了，很失落",
    "只是想找個人待著",
    "想聊聊最近的煩心事",
    "拖延越來越嚴重",
    "做決定總是猶豫不決",
    "總是忍不住刷手機到很晚",
    "生氣的時候容易說重話",
    "不好意思開口請別人幫忙",
    "想學會好好照顧自己",
    "壓力大時不知道怎麼放鬆",
    "有件事一直放不下",
    "害怕衝突，總是忍著",
    "和朋友因為借錢鬧僵了",
    "感覺被同事排擠",
    "產假結束要回去上班了，很忐忑",
    "退休後不知道做什麼好",
    "心裡有個結，想理一理",
  ],
  en: [
    "Work stress has me wound up tight",
    "Overtime every day leaves me drained",
    "My boss always finds fault with me",
    "Dealing with coworkers wears me out",
    "I want to quit but I'm afraid to",
    "I just lost my job and I'm anxious",
    "Job hunting keeps going nowhere",
    "I'm not sure I should stay in this job",
    "I got passed over for promotion",
    "My work doesn't feel meaningful",
    "I get nervous speaking up in meetings",
    "My mind keeps racing after work",
    "I'm new at work and feel clueless",
    "Sunday evenings I start dreading work",
    "I've been given more tasks than I can finish",
    "Grad school entrance exams are stressing me out",
    "I've failed the civil service exam several times",
    "I graduated and don't know where to go next",
    "My thesis is stuck",
    "I feel lost in my graduate program",
    "My partner and I keep arguing",
    "We just broke up and I can't let go",
    "Long distance is wearing me out",
    "I feel like my partner doesn't care",
    "Family keeps pushing me to get married",
    "Married life isn't what I imagined",
    "I don't know whether to stay in this relationship",
    "I've been single a long time and feel lonely",
    "I always give in too much in relationships",
    "I found out my partner is hiding something",
    "Talking with my parents always goes badly",
    "My parents are getting older and I worry",
    "My upbringing still affects me",
    "Being a parent feels like more than I can handle",
    "My kid won't listen and I'm running out of patience",
    "I can't keep up with both childcare and work",
    "My family and I see things so differently",
    "Everything at home falls on me",
    "Caring for a sick family member is exhausting",
    "I'm dreading going home for the holidays",
    "I moved to a new city and don't have a single friend",
    "I have fewer and fewer friends",
    "Social situations always feel awkward",
    "I don't know how to say no",
    "I feel like I'm always trying to please people",
    "After work I just want to be alone",
    "I'm drifting apart from old friends",
    "I feel lonely even in a crowd",
    "My mind's been a bit messy lately, I want to talk",
    "I often feel anxious for no clear reason",
    "I've been feeling low for a while",
    "Little things set me off",
    "I'm worn out inside but can't say why",
    "I always expect the worst",
    "I can't stop my mind from churning",
    "I get really sad when I'm alone",
    "I feel like I'm constantly draining myself",
    "When emotions hit, I don't know what to do",
    "I haven't been sleeping well",
    "I keep waking up at night and can't fall back asleep",
    "I feel tired every single day",
    "My sleep schedule is a mess and I can't fix it",
    "I eat a lot when I'm stressed",
    "I keep worrying something is wrong with my health",
    "I feel like I've achieved nothing",
    "I keep comparing myself with people my age",
    "I'm thirty and still feel lost",
    "I demand too much of myself and can't let up",
    "It's hard to accept that I'm not perfect",
    "I don't know what I really want",
    "I never feel good enough",
    "I want to change but stay stuck",
    "I care a lot about how others judge me",
    "My confidence keeps slipping",
    "Money worries make me anxious",
    "My mortgage is wearing me down",
    "I can't save money and feel insecure",
    "I still haven't settled in after moving",
    "Life feels like nothing but work and sleep",
    "Every day feels the same",
    "I can't move on since a family member passed away",
    "My pet is gone and I feel empty",
    "I've been through some upheaval and haven't recovered",
    "A friendship ended and I'm sad about it",
    "I just want some company",
    "I'd like to talk about what's been bothering me",
    "My procrastination keeps getting worse",
    "I can never make up my mind",
    "I stay up late scrolling on my phone",
    "I say harsh things when I'm angry",
    "I find it hard to ask others for help",
    "I want to learn to take better care of myself",
    "I don't know how to relax when I'm stressed",
    "There's something I can't let go of",
    "I avoid conflict and keep everything in",
    "Lending money to a friend went sour",
    "I feel shut out by my coworkers",
    "My parental leave is ending and I'm nervous about going back",
    "I've retired and don't know what to do with myself",
    "Something's knotted up inside and I want to untangle it",
  ],
  ja: [
    "仕事のプレッシャーで気が張りつめている",
    "毎日残業で、すっかり消耗している",
    "上司にいつもダメ出しされる",
    "同僚との付き合いに疲れる",
    "辞めたいけど、踏み出せない",
    "失業したばかりで不安",
    "就職活動がうまくいかない",
    "この仕事を続けるべきかわからない",
    "昇進を見送られて落ち込んでいる",
    "仕事にやりがいを感じない",
    "会議で発言するのが緊張する",
    "仕事が終わっても頭が休まらない",
    "新人で何もわからない",
    "日曜の夜になると仕事が憂うつ",
    "終わらないほどの仕事を任された",
    "大学院入試のプレッシャーが大きい",
    "公務員試験に何度も落ちている",
    "卒業後どうすればいいかわからない",
    "論文が進まない",
    "大学院生活に迷っている",
    "パートナーとケンカばかり",
    "別れたばかりで、気持ちの整理がつかない",
    "遠距離恋愛に疲れた",
    "パートナーに大切にされていない気がする",
    "結婚をせかされてしんどい",
    "結婚生活が思っていたのと違う",
    "この関係を続けるべきか迷っている",
    "一人の時間が長くて、さみしい",
    "恋愛でいつも自分ががまんしてしまう",
    "パートナーが何か隠している",
    "親とうまく話せない",
    "親が年をとってきて心配",
    "育った家庭の影響がずっと残っている",
    "親になって、手に負えないと感じる",
    "子どもが言うことを聞かなくて、余裕がない",
    "子育てと仕事の両立ができない",
    "家族と価値観が合わない",
    "家のことが全部自分にのしかかっている",
    "病気の家族の介護で疲れきっている",
    "年末年始の帰省が気が重い",
    "新しい街に来て、友だちが一人もいない",
    "友だちがどんどん減っている",
    "人の集まりではいつも気まずい",
    "人の頼みを断れない",
    "いつも人に合わせてばかりいる気がする",
    "仕事のあとは一人でいたい",
    "昔の友だちと疎遠になってきた",
    "人の中にいても孤独を感じる",
    "最近心がごちゃごちゃしていて、話したい",
    "理由もなく不安になる",
    "しばらく気分が落ち込んでいる",
    "小さなことでカッとなる",
    "心が疲れているけど、理由がわからない",
    "いつも最悪のことを考えてしまう",
    "頭の中で考えごとが止まらない",
    "一人になると悲しくなりやすい",
    "ずっと自分をすり減らしている気がする",
    "感情があふれたとき、どうすればいいかわからない",
    "最近あまり眠れていない",
    "夜中に何度も目が覚めて、眠れなくなる",
    "毎日ずっと疲れている",
    "生活リズムが崩れて戻せない",
    "ストレスがたまると食べすぎてしまう",
    "体のことがいつも心配",
    "自分は何も成し遂げていない気がする",
    "同年代の人とつい比べてしまう",
    "三十になっても迷っている",
    "自分に厳しすぎて、休めない",
    "完璧じゃない自分を受け入れられない",
    "本当に何をしたいのかわからない",
    "自分はいつも足りないと思ってしまう",
    "変わりたいのに足踏みしている",
    "人の評価が気になって仕方ない",
    "自信がどんどんなくなっている",
    "お金のことで不安",
    "住宅ローンが重くのしかかっている",
    "貯金ができなくて不安",
    "引っ越してからなじめない",
    "生活が仕事と睡眠だけになっている",
    "毎日が同じことのくり返し",
    "家族を亡くしてから立ち直れない",
    "ペットがいなくなって、心にぽっかり穴があいた",
    "いろいろあって、まだ立ち直れていない",
    "友だちとの関係が終わって、落ち込んでいる",
    "ただ誰かにそばにいてほしい",
    "最近の悩みを聞いてほしい",
    "先延ばしがひどくなってきた",
    "なかなか決められない",
    "夜遅くまでスマホを見てしまう",
    "怒るときつい言葉を言ってしまう",
    "人に助けを頼むのが苦手",
    "自分を大切にする方法を知りたい",
    "ストレスがたまったときの休み方がわからない",
    "ずっと引きずっていることがある",
    "衝突がこわくて、いつもがまんしてしまう",
    "友だちとのお金の貸し借りで気まずくなった",
    "職場で浮いている気がする",
    "育休明けの復帰が不安",
    "退職してから何をすればいいかわからない",
    "心にひっかかっていることを整理したい",
  ],
  ko: [
    "업무 스트레스 때문에 늘 긴장해 있어",
    "매일 야근해서 기운이 하나도 없어",
    "상사가 늘 내 흠을 잡아",
    "동료들과 지내는 게 피곤해",
    "퇴사하고 싶은데 용기가 안 나",
    "얼마 전에 일자리를 잃어서 불안해",
    "취업 준비가 계속 잘 안 돼",
    "이 일을 계속해야 할지 모르겠어",
    "승진에서 밀려서 속상해",
    "일에서 보람을 못 느껴",
    "회의에서 발표만 하면 긴장돼",
    "퇴근해도 머리가 쉬지를 않아",
    "신입이라 아무것도 모르겠어",
    "일요일 밤만 되면 출근이 걱정돼",
    "끝낼 수 없을 만큼 일이 쌓였어",
    "대학원 입시 준비가 너무 부담돼",
    "공무원 시험에 몇 번이나 떨어졌어",
    "졸업했는데 어디로 가야 할지 모르겠어",
    "논문이 진도가 안 나가",
    "대학원 생활이 막막해",
    "연인이랑 자꾸 싸워",
    "막 헤어졌는데 잊히지가 않아",
    "장거리 연애가 너무 지쳐",
    "상대가 나를 신경 안 쓰는 것 같아",
    "결혼하라는 압박이 너무 커",
    "결혼 생활이 상상했던 거랑 달라",
    "이 관계를 계속해야 할지 모르겠어",
    "혼자 지낸 지 오래돼서 외로워",
    "연애할 때 늘 내가 참게 돼",
    "연인이 뭔가 숨기는 것 같아",
    "부모님과 대화가 늘 불편하게 끝나",
    "부모님이 나이 드셔서 걱정돼",
    "자라온 가정의 영향이 계속 남아 있어",
    "부모가 되고 나니 감당하기 버거워",
    "아이가 말을 안 들어서 인내심이 바닥났어",
    "육아와 일을 둘 다 챙기기 힘들어",
    "가족이랑 생각이 너무 달라",
    "집안일이 다 나한테 몰려",
    "아픈 가족을 돌보느라 지쳤어",
    "명절에 본가 가는 게 부담돼",
    "새 도시로 왔는데 친구가 한 명도 없어",
    "친구가 점점 줄어",
    "모임 자리는 늘 어색해",
    "거절하는 법을 모르겠어",
    "늘 남의 비위를 맞추는 것 같아",
    "퇴근하면 혼자 있고 싶어",
    "오랜 친구들과 점점 멀어졌어",
    "사람들 속에 있어도 외로워",
    "요즘 마음이 좀 복잡해서 얘기하고 싶어",
    "이유 없이 불안할 때가 많아",
    "한동안 기분이 가라앉아 있어",
    "작은 일에도 쉽게 욱해",
    "마음이 지쳤는데 이유를 모르겠어",
    "늘 최악의 상황부터 떠올라",
    "생각이 멈추질 않아",
    "혼자 있을 때 특히 슬퍼져",
    "계속 나를 소모하고 있는 것 같아",
    "감정이 올라오면 어떻게 해야 할지 모르겠어",
    "요즘 잠을 잘 못 자",
    "밤중에 자꾸 깨고 다시 잠들기 어려워",
    "매일 너무 피곤해",
    "생활 리듬이 무너져서 못 돌리겠어",
    "스트레스 받으면 많이 먹게 돼",
    "건강에 문제가 있을까 봐 늘 걱정돼",
    "이룬 게 하나도 없는 것 같아",
    "자꾸 또래랑 비교하게 돼",
    "서른인데 아직도 막막해",
    "나 자신한테 너무 엄격해서 쉬지를 못해",
    "완벽하지 않은 나를 받아들이기 어려워",
    "내가 진짜 원하는 게 뭔지 모르겠어",
    "나는 늘 부족한 것 같아",
    "바뀌고 싶은데 제자리걸음이야",
    "남의 평가가 너무 신경 쓰여",
    "자신감이 점점 떨어져",
    "돈 걱정 때문에 불안해",
    "대출 갚느라 너무 지쳐",
    "저축을 못 해서 불안해",
    "이사 온 뒤로 적응이 안 돼",
    "생활이 출근하고 자는 것밖에 없어",
    "매일이 똑같아",
    "가족을 떠나보낸 뒤로 계속 힘들어",
    "반려동물이 떠나서 마음이 텅 빈 것 같아",
    "큰일을 겪고 아직 회복이 안 됐어",
    "친구와의 관계가 끝나서 속상해",
    "그냥 누가 곁에 있어 줬으면 좋겠어",
    "요즘 고민을 좀 털어놓고 싶어",
    "미루는 습관이 점점 심해져",
    "결정을 늘 못 내리겠어",
    "밤늦게까지 휴대폰을 보게 돼",
    "화나면 말을 심하게 해",
    "남에게 도움을 청하는 게 어려워",
    "나를 잘 돌보는 법을 배우고 싶어",
    "스트레스 받을 때 어떻게 쉬어야 할지 모르겠어",
    "계속 마음에 걸리는 일이 있어",
    "갈등이 무서워서 늘 참아",
    "친구랑 돈 문제로 사이가 틀어졌어",
    "직장에서 따돌림받는 것 같아",
    "육아휴직이 끝나서 복직이 걱정돼",
    "은퇴하고 나니 뭘 해야 할지 모르겠어",
    "마음속 응어리를 좀 풀고 싶어",
  ],
  es: [
    "El estrés del trabajo me tiene en tensión todo el día",
    "Hago horas extra cada día y acabo sin energía",
    "Mi jefe siempre me saca defectos",
    "Tratar con mis compañeros de trabajo me agota",
    "Quiero dejar el trabajo pero no me atrevo",
    "Acabo de quedarme sin trabajo y me angustia",
    "Busco trabajo y no paro de recibir negativas",
    "No sé si debería seguir en este trabajo",
    "No me dieron el ascenso y me ha frustrado",
    "Mi trabajo no me llena",
    "Hablar en las reuniones me pone de los nervios",
    "Salgo del trabajo y mi cabeza no para",
    "Acabo de empezar en el trabajo y no sé por dónde tirar",
    "Los domingos por la noche ya me agobia el lunes",
    "Me han encargado más tareas de las que puedo hacer",
    "Preparar el acceso al máster me agobia mucho",
    "He suspendido las oposiciones varias veces",
    "Terminé la carrera y no sé hacia dónde ir",
    "Mi tesis está atascada",
    "No sé qué rumbo tomar en el posgrado",
    "Mi pareja y yo discutimos todo el tiempo",
    "Acabamos de romper y no consigo pasar página",
    "La relación a distancia me está agotando",
    "Siento que a mi pareja no le importo",
    "Me presionan para que me case",
    "La vida de casados no es como imaginaba",
    "No sé si seguir con esta relación",
    "Llevo mucho tiempo sin pareja y noto la soledad",
    "En las relaciones siempre acabo cediendo de más",
    "He descubierto que mi pareja me oculta algo",
    "Hablar con mis padres siempre acaba mal",
    "Mis padres se hacen mayores y me preocupan",
    "Lo que viví en mi familia de origen todavía me afecta",
    "Ser madre o padre me está superando",
    "Mi hijo no me hace caso y se me acaba la paciencia",
    "No llego a todo entre la crianza y el trabajo",
    "Mi familia y yo pensamos muy distinto",
    "Todo lo de casa recae sobre mí",
    "Cuidar a un familiar enfermo me está agotando",
    "Volver a casa en las fiestas me pesa",
    "Me mudé a una ciudad nueva y no tengo ni un amigo",
    "Cada vez tengo menos amigos",
    "En los eventos sociales me siento fuera de lugar",
    "No sé decir que no",
    "Siento que siempre intento complacer a todos",
    "Después del trabajo solo quiero estar a solas",
    "Me estoy distanciando de mis viejos amigos",
    "Incluso entre mucha gente siento soledad",
    "Últimamente tengo la cabeza hecha un lío y quiero hablar",
    "Me entra ansiedad sin motivo claro",
    "Llevo un tiempo con el ánimo bajo",
    "Las pequeñas cosas me sacan de quicio",
    "Estoy con el alma cansada y no sé por qué",
    "Siempre me pongo en lo peor",
    "Mi mente no deja de dar vueltas",
    "Cuando estoy a solas me entristezco con facilidad",
    "Siento que me desgasto todo el tiempo",
    "Cuando me desbordan las emociones no sé qué hacer",
    "Últimamente no duermo bien",
    "Me despierto de madrugada y ya no puedo volver a dormir",
    "El cansancio no se me va",
    "Tengo los horarios descolocados y no consigo arreglarlos",
    "Con estrés como de más",
    "Siempre me preocupa tener algún problema de salud",
    "Siento que no he logrado nada",
    "Siempre me comparo con gente de mi edad",
    "Tengo treinta años y sigo sin rumbo",
    "Me exijo demasiado y no sé parar",
    "Me cuesta aceptar mis imperfecciones",
    "No sé lo que quiero de verdad",
    "Nunca me siento suficiente",
    "Quiero cambiar pero no avanzo",
    "Me importa mucho cómo me juzgan los demás",
    "Mi autoestima va a menos",
    "Las preocupaciones económicas me angustian",
    "La hipoteca me pesa muchísimo",
    "No consigo ahorrar y me genera inseguridad",
    "Me mudé y todavía no me adapto",
    "Mi vida se ha reducido a trabajar y dormir",
    "Todos los días son iguales",
    "Desde que murió un familiar no consigo salir adelante",
    "Se fue mi mascota y siento un vacío",
    "He pasado por cambios fuertes y aún no me recupero",
    "Se acabó una amistad y estoy triste",
    "Solo quiero un poco de compañía",
    "Me gustaría hablar de lo que me preocupa últimamente",
    "Cada vez procrastino más",
    "Me cuesta muchísimo tomar decisiones",
    "Me quedo hasta tarde mirando el móvil",
    "Cuando me enfado digo cosas duras",
    "Me cuesta pedir ayuda a los demás",
    "Quiero aprender a cuidarme mejor",
    "No sé cómo relajarme con tanto estrés",
    "Hay algo que no consigo soltar",
    "Me dan miedo los conflictos y me lo trago todo",
    "Prestarle dinero a un amigo acabó en mal rollo",
    "Siento que mis compañeros de trabajo me excluyen",
    "Se acaba mi permiso parental y me dan nervios volver",
    "Me he jubilado y no sé qué hacer con mi tiempo",
    "Tengo un nudo por dentro y quiero desenredarlo",
  ],
  fr: [
    "Le stress du travail me met sous tension en permanence",
    "Je fais des heures sup tous les jours et je suis vidé",
    "Mon chef me reproche toujours quelque chose",
    "Les relations avec mes collègues m’épuisent",
    "J’ai envie de démissionner mais je n’ose pas",
    "Je viens de perdre mon travail et je suis angoissé",
    "Je cherche du travail et ça ne mène à rien",
    "Je ne sais pas si je dois rester dans ce poste",
    "Je n’ai pas eu la promotion et je suis déçu",
    "Mon travail n’a plus de sens pour moi",
    "Prendre la parole en réunion me stresse",
    "Après le travail, mon cerveau ne s’arrête pas",
    "Je suis nouveau au travail et je me sens perdu",
    "Le dimanche soir, je redoute déjà le lundi",
    "On m’a confié plus de tâches que je ne peux en faire",
    "Préparer les concours du master me met une grosse pression",
    "J’ai raté plusieurs fois le concours de la fonction publique",
    "J’ai fini mes études et je ne sais pas où aller",
    "Mon mémoire n’avance plus",
    "Je me sens perdu dans mes études supérieures",
    "Avec mon partenaire, on se dispute sans arrêt",
    "On vient de rompre et je n’arrive pas à tourner la page",
    "La relation à distance m’épuise",
    "J’ai l’impression de ne pas compter pour mon partenaire",
    "On me met la pression pour que je me marie",
    "La vie de couple ne ressemble pas à ce que j’imaginais",
    "Je ne sais pas si je dois continuer cette relation",
    "Je suis célibataire depuis longtemps et je me sens seul",
    "Dans mes relations, je m’efface toujours",
    "J’ai découvert que mon partenaire me cache quelque chose",
    "Parler avec mes parents se passe toujours mal",
    "Mes parents vieillissent et je m’inquiète pour eux",
    "Ce que j’ai vécu dans ma famille me pèse encore",
    "Être parent me dépasse un peu",
    "Mon enfant n’écoute rien et je suis à bout de patience",
    "Je n’arrive pas à concilier enfants et travail",
    "Ma famille et moi, on ne voit pas les choses pareil",
    "Tout ce qui concerne la maison repose sur moi",
    "M’occuper d’un proche malade m’épuise",
    "Rentrer en famille pour les fêtes m’angoisse un peu",
    "J’ai déménagé dans une nouvelle ville et je n’ai aucun ami",
    "J’ai de moins en moins d’amis",
    "En soirée, je me sens toujours mal à l’aise",
    "Je ne sais pas dire non",
    "J’ai l’impression de toujours chercher à faire plaisir",
    "Après le travail, je veux juste être tranquille",
    "Je m’éloigne de mes vieux amis",
    "Je me sens seul même entouré de monde",
    "J’ai la tête en vrac ces temps-ci, j’ai envie d’en parler",
    "Je suis souvent anxieux sans raison",
    "J’ai le moral en baisse depuis un moment",
    "Un rien me met en colère",
    "Je suis fatigué intérieurement sans savoir pourquoi",
    "J’imagine toujours le pire",
    "Je n’arrive pas à arrêter de ruminer",
    "Quand je suis seul, la tristesse arrive vite",
    "J’ai l’impression de m’user à petit feu",
    "Quand les émotions débordent, je ne sais pas quoi faire",
    "Je dors mal ces temps-ci",
    "Je me réveille la nuit et je n’arrive plus à me rendormir",
    "Je suis fatigué tous les jours",
    "Mon rythme de sommeil est déréglé et je n’arrive pas à le rattraper",
    "Quand je suis stressé, je mange beaucoup",
    "Je m’inquiète sans cesse pour ma santé",
    "J’ai l’impression de n’avoir rien accompli",
    "Je me compare toujours aux gens de mon âge",
    "J’ai trente ans et je suis encore perdu",
    "Je suis trop exigeant avec moi-même et je ne sais pas lever le pied",
    "J’ai du mal à accepter de ne pas être parfait",
    "Je ne sais pas ce que je veux vraiment",
    "Je n’ai jamais l’impression d’être à la hauteur",
    "Je veux changer, mais je fais du surplace",
    "Le jugement des autres compte beaucoup trop pour moi",
    "Ma confiance en moi s’effrite",
    "Les soucis d’argent m’angoissent",
    "Mon crédit immobilier me pèse énormément",
    "Je n’arrive pas à mettre de l’argent de côté et ça m’insécurise",
    "Depuis mon déménagement, je n’arrive pas à m’adapter",
    "Ma vie se résume à travailler et dormir",
    "Tous les jours se ressemblent",
    "Depuis le décès d’un proche, je n’arrive pas à remonter la pente",
    "Mon animal est parti et je me sens vide",
    "J’ai traversé des bouleversements et je ne m’en suis pas remis",
    "Une amitié s’est terminée et ça me rend triste",
    "J’ai juste besoin de compagnie",
    "J’aimerais parler de ce qui me tracasse en ce moment",
    "Je procrastine de plus en plus",
    "J’hésite toujours à prendre des décisions",
    "Je traîne sur mon téléphone jusque tard le soir",
    "Quand je suis en colère, je dis des mots durs",
    "J’ai du mal à demander de l’aide",
    "J’aimerais apprendre à mieux prendre soin de moi",
    "Je ne sais pas comment me détendre quand je suis stressé",
    "Il y a quelque chose que je n’arrive pas à lâcher",
    "J’ai peur des conflits, alors je garde tout pour moi",
    "Une histoire d’argent prêté à un ami a mal tourné",
    "J’ai l’impression d’être mis à l’écart par mes collègues",
    "Mon congé parental se termine et j’appréhende la reprise",
    "Je suis à la retraite et je ne sais pas quoi faire de mes journées",
    "J’ai un nœud à l’intérieur que j’aimerais démêler",
  ],
  de: [
    "Der Druck bei der Arbeit lässt mich ständig angespannt sein",
    "Jeden Tag Überstunden, ich bin völlig ausgelaugt",
    "Mein Chef findet immer etwas auszusetzen",
    "Der Umgang mit Kollegen erschöpft mich",
    "Ich will kündigen, traue mich aber nicht",
    "Ich habe gerade meinen Job verloren und habe Angst",
    "Die Jobsuche läuft ins Leere",
    "Ich weiß nicht, ob ich in diesem Job bleiben soll",
    "Bei der Beförderung wurde ich übergangen",
    "Meine Arbeit erfüllt mich nicht",
    "In Meetings zu sprechen macht mich nervös",
    "Nach Feierabend hört mein Kopf nicht auf",
    "Ich bin neu im Job und fühle mich ahnungslos",
    "Am Sonntagabend graut mir schon vor der Arbeit",
    "Ich habe mehr Aufgaben bekommen, als ich schaffen kann",
    "Die Vorbereitung auf die Masterzulassung setzt mich unter Druck",
    "Ich bin mehrmals durch die Prüfung für den öffentlichen Dienst gefallen",
    "Ich habe mein Studium beendet und weiß nicht, wohin",
    "Meine Abschlussarbeit kommt nicht voran",
    "Im Masterstudium bin ich orientierungslos",
    "In meiner Beziehung streiten wir ständig",
    "Wir haben uns gerade getrennt und ich komme nicht davon los",
    "Die Fernbeziehung zehrt an mir",
    "Ich habe das Gefühl, in meiner Beziehung nicht wichtig zu sein",
    "Ich werde ständig gedrängt zu heiraten",
    "Das Eheleben ist anders, als ich es mir vorgestellt habe",
    "Ich weiß nicht, ob ich diese Beziehung weiterführen soll",
    "Ich bin schon lange Single und fühle mich einsam",
    "In Beziehungen stecke ich immer zurück",
    "Ich habe herausgefunden, dass mir in meiner Beziehung etwas verheimlicht wird",
    "Gespräche mit meinen Eltern laufen immer schlecht",
    "Meine Eltern werden älter und ich mache mir Sorgen",
    "Meine Herkunftsfamilie prägt mich immer noch",
    "Als Elternteil fühle ich mich überfordert",
    "Mein Kind hört nicht und meine Geduld ist am Ende",
    "Kinder und Job bekomme ich nicht unter einen Hut",
    "Meine Familie und ich sehen vieles ganz anders",
    "Alles im Haushalt bleibt an mir hängen",
    "Die Pflege eines kranken Angehörigen erschöpft mich",
    "Vor dem Familienbesuch an den Feiertagen graut mir",
    "Ich bin in eine neue Stadt gezogen und kenne niemanden",
    "Ich habe immer weniger Freunde",
    "Bei geselligen Anlässen fühle ich mich immer unwohl",
    "Ich kann nicht Nein sagen",
    "Ich habe das Gefühl, es immer allen recht machen zu wollen",
    "Nach der Arbeit will ich einfach meine Ruhe",
    "Ich entferne mich von alten Freunden",
    "Selbst unter vielen Menschen fühle ich mich einsam",
    "In meinem Kopf ist gerade viel durcheinander, ich will reden",
    "Ich bin oft ohne Grund ängstlich",
    "Ich bin schon eine Weile niedergeschlagen",
    "Kleinigkeiten bringen mich auf die Palme",
    "Ich bin innerlich erschöpft und weiß nicht, warum",
    "Ich rechne immer mit dem Schlimmsten",
    "Meine Gedanken kreisen ununterbrochen",
    "Wenn ich allein bin, werde ich schnell traurig",
    "Ich habe das Gefühl, mich ständig aufzureiben",
    "Wenn Gefühle hochkommen, weiß ich nicht, was ich tun soll",
    "Ich schlafe in letzter Zeit schlecht",
    "Ich wache nachts auf und kann nicht wieder einschlafen",
    "Ich bin jeden Tag müde",
    "Mein Schlafrhythmus ist durcheinander und ich bekomme ihn nicht hin",
    "Wenn ich gestresst bin, esse ich viel",
    "Ich mache mir ständig Sorgen um meine Gesundheit",
    "Ich habe das Gefühl, nichts erreicht zu haben",
    "Ich vergleiche mich ständig mit Gleichaltrigen",
    "Ich bin dreißig und immer noch orientierungslos",
    "Ich verlange zu viel von mir und kann nicht abschalten",
    "Es fällt mir schwer, nicht perfekt zu sein",
    "Ich weiß nicht, was ich wirklich will",
    "Ich fühle mich nie gut genug",
    "Ich will mich ändern, trete aber auf der Stelle",
    "Mir ist sehr wichtig, wie andere mich bewerten",
    "Mein Selbstvertrauen schwindet",
    "Geldsorgen machen mir Angst",
    "Der Kredit für die Wohnung belastet mich sehr",
    "Ich kann nichts sparen und fühle mich unsicher",
    "Seit dem Umzug komme ich nicht richtig an",
    "Mein Leben besteht nur noch aus Arbeit und Schlaf",
    "Jeder Tag ist gleich",
    "Seit ein Angehöriger gestorben ist, komme ich nicht wieder auf die Beine",
    "Mein Haustier ist nicht mehr da und ich fühle mich leer",
    "Ich habe einiges durchgemacht und mich noch nicht erholt",
    "Eine Freundschaft ist zu Ende und das macht mich traurig",
    "Ich hätte einfach gern etwas Gesellschaft",
    "Ich möchte über das reden, was mich gerade beschäftigt",
    "Ich schiebe immer mehr auf",
    "Entscheidungen fallen mir unglaublich schwer",
    "Ich hänge abends lange am Handy",
    "Wenn ich wütend bin, sage ich harte Dinge",
    "Es fällt mir schwer, um Hilfe zu bitten",
    "Ich möchte lernen, besser für mich zu sorgen",
    "Ich weiß nicht, wie ich bei Stress abschalten kann",
    "Es gibt etwas, das ich nicht loslassen kann",
    "Ich habe Angst vor Konflikten und schlucke alles runter",
    "Wegen geliehenem Geld ist es mit einem Freund schwierig geworden",
    "Ich fühle mich von Kollegen ausgegrenzt",
    "Meine Elternzeit endet und mir graut vor dem Wiedereinstieg",
    "Ich bin in Rente und weiß nicht, was ich mit mir anfangen soll",
    "Da ist ein Knoten in mir, den ich gern lösen würde",
  ],
};

export function starterAudience(ageRange: AgeRange): "teen" | "adult" {
  return ageRange === "minor" ? "teen" : "adult";
}

const CJK = /[\u3040-\u30ff\u3400-\u9fff\uac00-\ud7af]/;
const HANGUL = /[\uac00-\ud7af]/;
const HIRAGANA_ONLY = /^[\u3040-\u309f]+$/;
// Everyday words that say nothing about the topic; matching on them would look random.
const STOP = new Set([
  "有点", "感觉", "最近", "知道", "不知道", "什么", "怎么", "怎么办", "自己", "觉得", "好像", "总是", "一直", "时候", "没有", "不想", "不敢",
  "一个", "这个", "那个", "还是", "就是", "但是", "因为", "所以", "可以", "现在", "今天", "真的", "已经", "其实", "心里", "我们", "他们",
  "一些", "很多", "不是", "这样", "为什么", "不会", "不能", "应该", "有點", "感覺", "現在", "這個", "還是", "覺得", "沒有", "時候", "為什麼", "應該",
  "about", "becau", "there", "their", "would", "could", "shoul", "somet", "every", "reall", "think", "feeli", "being", "still", "again",
  "alway", "never", "right", "these", "those", "which", "where", "while", "after", "befor", "doesn", "don't", "can't", "thing", "latel",
  "dont", "cant", "just", "like", "feel", "want", "know", "with", "that", "this", "have", "what", "when", "they", "them", "from", "even",
  "much", "some", "more", "keep", "make", "been", "into", "than", "very",
  "없어", "있어", "하고", "해서", "너무", "정말", "그냥", "같아", "싶어", "어떻", "모르", "요즘", "계속", "자꾸", "뭔가", "어떡",
]);

/** Topic words via the browser's word segmenter: CJK words of 2+ characters (Korean cut to
 * a 2-syllable stem, grammar-only hiragana dropped), other words of 4+ letters cut to 5.
 * Without Intl.Segmenter there are no topic words and the draw stays random. */
function topicTokens(text: string, lang: Lang): string[] {
  if (typeof Intl === "undefined" || !("Segmenter" in Intl)) return [];
  const out: string[] = [];
  for (const { segment, isWordLike } of new Intl.Segmenter(lang, { granularity: "word" }).segment(text.toLowerCase())) {
    if (!isWordLike || HIRAGANA_ONLY.test(segment)) continue;
    const cjk = CJK.test(segment);
    const token = HANGUL.test(segment) ? segment.slice(0, 2) : cjk ? segment : segment.slice(0, 5);
    if ((cjk ? token.length >= 2 : segment.length >= 4) && !STOP.has(token)) out.push(token);
  }
  return out;
}

/** `count` distinct openers for this language and age choice. With no history they are a
 * fresh random draw on every visit; with history (the user's past sessions, kept in this
 * browser) the openers sharing the most topic words with it come first, ties at random. */
export function pickStarters(lang: Lang, ageRange: AgeRange, count = 3, random: () => number = Math.random, history = ""): string[] {
  const pool = [...(starterAudience(ageRange) === "teen" ? TEEN_STARTERS : ADULT_STARTERS)[lang]];
  for (let i = pool.length - 1; i > 0; i -= 1) {
    const j = Math.floor(random() * (i + 1));
    [pool[i], pool[j]] = [pool[j], pool[i]];
  }
  const said = new Map<string, number>();
  for (const token of topicTokens(history, lang)) said.set(token, (said.get(token) ?? 0) + 1);
  if (!said.size) return pool.slice(0, count);
  // A word shared by many openers is generic; only fairly specific ones (in ≤3 openers) count.
  const tokensOf = new Map(pool.map((text) => [text, new Set(topicTokens(text, lang))]));
  const spread = new Map<string, number>();
  for (const tokens of tokensOf.values()) for (const token of tokens) spread.set(token, (spread.get(token) ?? 0) + 1);
  const score = (text: string) => [...tokensOf.get(text)!].reduce((sum, token) => sum + ((spread.get(token) ?? 0) <= 3 ? said.get(token) ?? 0 : 0), 0);
  const related = pool.map((text) => ({ text, score: score(text) })).filter((item) => item.score > 0)
    .sort((a, b) => b.score - a.score).slice(0, count).map((item) => item.text);
  return [...related, ...pool.filter((text) => !related.includes(text))].slice(0, count);
}
